# Usa Node 20 (puede ser alpine o slim)
FROM --platform=linux/amd64 node:20-alpine

# Crea el directorio de trabajo
WORKDIR /usr/src/app

# Copia dependencias
COPY package*.json ./
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto de desarrollo de Vite
EXPOSE 5173

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host"]
