# Dockerfile
FROM node:18

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar solo los archivos del backend
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código del backend
COPY . .

# Exponer el puerto del backend
EXPOSE 3000

# Comando para iniciar la app
CMD ["npm", "start"]
